# Site settings
name: Beach Site
email: zangshayang1@hotmail.com
author: Shayang Zang
url: 
resume_site: 
github: https://github.com/zangshayang1/
baseurl: ""
description: No time for description.
meta_description: 中科星龙的静态博客。
motto: 中科星龙
banner: 诚信经营 追求卓越


#permalink: /:year/:month/:day/:title/
markdown: kramdown
permalink: pretty

#paginate: 10

#include: ['jekyll-paginate', 'rouge']
#exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zangshayang1

# Build settings
highlighter: rouge
kramdown:
    auto_ids: true
    input: GFM
    syntax_highlighter: rouge


FB:
  comments :
    provider : disqus
    disqus :
        short_name : zangshayang1-github-io
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
